[workspace]
name = "etlegacy-demosummaries"
authors = ["Vorschreibung"]
version = "1.0.0"
channels = [
    "conda-forge",
]

platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
"build" = { cmd = ["go", "run", "./build-tool/main.go", "-a"] }

[dependencies]
"go" = "*"

